import engine from "form-engine";

const api = engine && engine.validateField ? engine : engine.default || engine;

export const createId = api.createId;
export const toFieldKey = api.toFieldKey;
export const uniqueKey = api.uniqueKey;
export const nextVersionLabel = api.nextVersionLabel;
export const countryOptions = api.countryOptions;
export const stateOptions = api.stateOptions;
export const FIELD_TYPES = api.FIELD_TYPES;
export const BASIC_FIELD_TYPES = api.BASIC_FIELD_TYPES;
export const ADVANCED_FIELD_TYPES = api.ADVANCED_FIELD_TYPES;
export const fieldTypeMeta = api.fieldTypeMeta;
export const operatorsForField = api.operatorsForField;
export const fieldSupportsProperty = api.fieldSupportsProperty;
export const fieldSupportsValidator = api.fieldSupportsValidator;
export const VALIDATOR_TYPES = api.VALIDATOR_TYPES;
export const validatorMeta = api.validatorMeta;
export const createValidator = api.createValidator;
export const operatorLabel = api.operatorLabel;
export const operatorNeedsValue = api.operatorNeedsValue;
export const operatorIsRange = api.operatorIsRange;
export const ACTION_TYPES = api.ACTION_TYPES;
export const ACTION_GROUPS = api.ACTION_GROUPS;
export const actionMeta = api.actionMeta;
export const createAction = api.createAction;
export const createSection = api.createSection;
export const createField = api.createField;
export const createOption = api.createOption;
export const createCondition = api.createCondition;
export const createConditionGroup = api.createConditionGroup;
export const createRule = api.createRule;
export const createDocument = api.createDocument;
export const createStage = api.createStage;
export const emptyDefinition = api.emptyDefinition;
export const cloneDefinition = api.cloneDefinition;
export const normalizeValue = api.normalizeValue;
export const validateField = api.validateField;
export const validateForm = api.validateForm;
export const evaluateGroup = api.evaluateGroup;
export const evaluateRule = api.evaluateRule;
export const evaluateRules = api.evaluateRules;
export const applyFieldChange = api.applyFieldChange;
export const initialDerivedState = api.initialDerivedState;
export const summarizeRule = api.summarizeRule;
export const formatSummaryText = api.formatSummaryText;
export const formatValue = api.formatValue;
export const validateFormConfiguration = api.validateFormConfiguration;
export const createSupplierOnboardingTemplate = api.createSupplierOnboardingTemplate;
export const createFrozenFoodPermitTemplate = api.createFrozenFoodPermitTemplate;

export default api;
